### ISSUE TITLE
Local Instance: How to run with out OAuth

### ISSUE THREAD

**Issue by hrishiballal** [wing-aviation/InterUSS-Platform#15]
Hello,
I am trying to run a local instance of this to test the API, the _ValidateAccessToken method basically raises a 403. What is a way to "test" out with Dummy credentials. I am setting the 'INTERUSS_PUBLIC_KEY' environment variable as 'Unused' 
Thanks!

**Comment by hi-kevin** [comment]
Hi Hirishi,
You'll need any valid OAuth service to do this. You can ignore the tests for now if you don't have that service available, and a complete test will be done when you make the Pull request. We always ensure test coverage before accepting in the main line branch.

**Comment by hi-kevin** [comment]
I am leaving this issue open, as we are in process of standing up InterUSS Platform OAuth servers to help with this.

**Comment by hrishiballal** [comment]
Hi Kevin, 
OK I tried to create sample credentials on Google Console -> Credentials. 

![cred](https://i.imgur.com/fFGth7g.png)

I set the `INTERUSS_PUBLIC_KEY` as my secret and the [token](https://github.com/wing-aviation/InterUSS-Platform/blob/master/datanode/src/storage_api.py#L209) as the client ID. 

When I relaunch the app and go to /introspect/ it is getting invalid_token error

![token](https://i.imgur.com/YojOfoN.png) 

I tried the same thing with GitHub credentials but the token cannot be validated, any suggestions? Would appreciate any help.

**Comment by hi-kevin** [comment]
Hi Hirishi, You need the Public Key from Google to be able to decrypt tokens, which probably isn't readily available. I wouldn't worry about this, we will do the full testing when you make a pull request, and another USS is working on hosting an OAuth specifically for InterUSS Platform USSs to use.

I know you are doing this for testing coverage, but just in case you are not aware, adding/replacing the -t gutma to the STORAGE_API_ARGS will allow you to use gutma (or gutma1, gutma2b, etc.) as your access token. It still won't introspect, but you'll be able to test all the other endpoints.

**Comment by hrishiballal** [comment]
OK thanks for this, I will try it out.

**Comment by hi-kevin** [comment]
Closing this issue as there is a way to test without a real OAuth server, as referenced above.
