### ISSUE TITLE
Sync token in OpenAPI needs format

### ISSUE THREAD

**Issue by nasajoey** [wing-aviation/InterUSS-Platform#16]
**Describe the bug**
In the OpenAPI for TCL4 (and probably v1.0), the sync_token is of type "integer".  This is OK, but since the description says "The zxid, which is a long (64-bit) integer", a format is needed for sync_token.  This is a problem when using codegen from the API as a 32-bit integer is generated for sync_token.

**To Reproduce**
1. Go to swagger hub
2. Click on export and choose Java client
3. Note this generated code:

```
public class JSendGridCellMetadataResponse {
...

  @SerializedName("sync_token")
  private Integer syncToken = null;
...
```
4. Edit API to add format field to sync token:

```
      sync_token:
        type: integer
        format: int64
```
5. Generate code as before.
6. Note difference:

```
public class JSendGridCellMetadataResponse {
...

  @SerializedName("sync_token")
  private Long syncToken = null;
...
```

**Expected behavior**
Codegen should produce correct data type for 64-bit sync token.

**Comment by hi-kevin** [comment]
Fixed! Version is still 4.0.1 since the API did not change, just the spec to match the API.

https://github.com/wing-aviation/InterUSS-Platform/commit/5ff16ca2100e976f63f028927e72d89f03d1934c
