### ISSUE TITLE
Specify required fields for response models on tcl4 branch

### ISSUE THREAD

**Issue by ktian94** [wing-aviation/InterUSS-Platform#22]
The below tcl4 models are missing a specification for required fields. @hi-kevin mentioned offline that all fields are likely required. Referenced from the [swaggerhub yaml](https://github.com/wing-aviation/InterUSS-Platform/blob/tcl4/assets/swaggerhub_api.yaml#L307).

- JSendStatusResponse
- JSendSlippyResponse
- JSendGridCellMetadataResponse
- GridCellMetadataResponse

**Comment by hi-kevin** [comment]
Fixed in swaggerhub and yaml has been posed to github.
