### ISSUE TITLE
Specify maxItems for operations in GridCellOperatorResponse

### ISSUE THREAD

**Issue by ktian94** [wing-aviation/InterUSS-Platform#23]
On the tcl4 branch, the maxItems specification is missing for the `operations` field in `GridCellOperatorResponse` in the [swaggerhub yaml](https://github.com/wing-aviation/InterUSS-Platform/blob/tcl4/assets/swaggerhub_api.yaml#L447). It was noted that it may have been missing due to an issue with adding a maxItems spec on an array of objects nested in an object, but it looks like we were able to [specify maxItems](https://github.com/wing-aviation/InterUSS-Platform/blob/tcl4/assets/swaggerhub_api.yaml#L374) for `operators` in `GridCellMetadataResponse`.

@hi-kevin mentioned that this number should be 1000.

**Comment by hi-kevin** [comment]
There is no validation done on the platform to limit the number of operations. Swaggerhub won't support documenting it legitimately. I suggest the real limit of the number of operations for a USS in a GridCell becomes a requirement out of TCL4.
