### ISSUE TITLE
Specify formats for POST / PUT data that can be submitted 

### ISSUE THREAD

**Issue by hrishiballal** [wing-aviation/InterUSS-Platform#25]
**Describe the bug**
I am running a test instance and submitting a PUT request to GridCellMetaData API endpoint. I get a 409 conflict with it. 

**To Reproduce**
1. Start Zookeeper
2. Start data_node with a the following command ```docker run -e INTERUSS_PUBLIC_KEY=Unused   -e STORAGE_API_ARGS="-t gutma"   -p 8121:8121   interussplatform/data_node```
3. Use curl or others to PUT the following ``` http://localhost:8121/GridCellMetaData/12/12/12?sync_token=44&scope=32&operation_endpoint=https://gutma.org/flightdeclarations&operation_format=GUTMA&minimum_operation_timestamp=2321&maximum_operation_timestamp=1232 ```
4. Get the following error:  
``` html <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>409 Conflict</title>
<h1>Conflict</h1>
<p>Content in metadata has been updated since provided sync token.</p>
```
**Additional context**
I checked the ```_PutGridCellMetaData``` code block and while the webargs have descritptions, it would be nice to have expected formats or samples that can be used for testing. 

I can do that if you can guide on the best way to do this.

**Comment by hi-kevin** [comment]
Hi Hirishi, you need the sync_token before you can PUT, which you would retrieve from a GET to the same grid cell. [Swaggerhub](https://app.swaggerhub.com/apis/InterUSS_Platform/data_node_api/) documents the API, as well as the [technical document](https://docs.google.com/document/d/1JtSvSnvskrctbCF8qsU7ZIMTzYegZtGDj4-a8kdC_Cs/).
