### ISSUE TITLE
Block slippy requests for invalid requests

### ISSUE THREAD

**Issue by hi-kevin** [wing-aviation/InterUSS-Platform#26]
**Describe the bug**
Currently you can request greater than 85 degrees latitude, which is not supported by slippy:
https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames

**To Reproduce**
`/slippy/0?coords=-86,0` returns `http://tile.openstreetmap.org/0/0/1.png` (nonexistent)
`/slippy/0?coords=89.999,0` returns `http://tile.openstreetmap.org/0/0/-1.png`

**Expected behavior**
4xx error for invalid format

**Comment by hrishiballal** [comment]
Is the fix changing the [_ValidateCoordinates](https://github.com/wing-aviation/InterUSS-Platform/blob/master/datanode/src/storage_api.py#L396) check?
