### ISSUE TITLE
Add an InterUSS Platform OAuth server

### ISSUE THREAD

**Issue by hi-kevin** [wing-aviation/InterUSS-Platform#4]
**Describe the bug**
Currently, the authorization uses a NASA public key to decode the access_token. (This is overridable in test mode by using the same token as your test instance, such as sandbox). This works fine for those that can create access tokens from NASA OAuth servers, but not for others.

**Expected behavior**
Create an InterUSS Platform OAuth server for use until the feature for region based OAuth is implemented.

**Additional context**
This OAuth server could be hosted by any of the InterUSS Platform participants.

**Comment by BenjaminPelletier** [comment]
This has been fulfilled in the publicportal branch.
