### ISSUE TITLE
Doc bug:  remove "InterUSS" from sequence diagrams for TCL4 branch

### ISSUE THREAD

**Issue by nasajoey** [wing-aviation/InterUSS-Platform#40]
**Describe the bug**
Since we are not using the trademarked InterUSS system in TCL4, we should scrub that from the diagrams in that branch.

I think it is only in the first line ("Title") of the following diagram source files, but I may be mistaken.

**Additional context**
https://github.com/wing-aviation/InterUSS-Platform/blob/tcl4/assets/USS1.sequence
https://github.com/wing-aviation/InterUSS-Platform/blob/tcl4/assets/USS2.sequence
https://github.com/wing-aviation/InterUSS-Platform/blob/tcl4/assets/USS3.sequence
https://github.com/wing-aviation/InterUSS-Platform/blob/tcl4/assets/USS4.sequence
https://github.com/wing-aviation/InterUSS-Platform/blob/tcl4/assets/USS5.sequence

**Comment by hi-kevin** [comment]
Resolved!
